### ISSUE TITLE
imagemin task not being found.

### ISSUE THREAD

**Issue by johnhornsby** [aaerox/cycle#14]
Using latest Cycle, returning this error

N:\Desktop\testchar>cycle
[cycle] Launching..
[cycle] Task list: task-copy task-concat task-uglify task-notify task-watch task
-sync task-sitecore task-bower task-javascript task-prototype task-styles task-a
utoprefixer task-imagemin task-waitexit
>> Local Npm module "grunt-contrib-imagemin" not found. Is it installed?

**Comment by lloydwheeler** [comment]
Fixed @johnhornsby
